name: Deploy VitePress Site

on:
  # 当代码推送到 master 分支时触发工作流
  push:
    branches:
      - master

jobs:
  deploy:
    # 将运行环境改为 Windows Server 2019 系统，你也可以选择 windows-2022
    runs-on: windows-2019

    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 构建 VitePress 项目
      - name: Build VitePress site
        run: npm run docs:build

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUP_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
